(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for long() with base 10: 'venda_praso'"
p3
sS'layer'
p4
S'/home/rogoberto/web2py/applications/abencoado/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f86a5037130, file "/home/rogoberto/web2py/applications/abencoado/controllers/default.py", line 8>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/rogoberto/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/rogoberto/web2py/applications/abencoado/controllers/default.py", line 161, in <module>\n  File "/home/rogoberto/web2py/gluon/globals.py", line 421, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/rogoberto/web2py/applications/abencoado/controllers/default.py", line 32, in venda_vista\n    rowsv += db(db.venda.sub_venda == l).select()\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/objects.py", line 2277, in select\n    return adapter.select(self.query, fields, attributes)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 758, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 673, in _select_wcols\n    query = self.expand(query, query_env=query_env)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 435, in _expand\n    rv = op(first, second, **optional_args)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/dialects/base.py", line 344, in eq\n    self.expand(second, first.type, query_env=query_env))\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/dialects/__init__.py", line 96, in expand\n    return self.adapter.expand(*args, **kwargs)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 445, in _expand\n    rv = self.represent(expression, field_type)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 382, in represent\n    return super(SQLAdapter, self).represent(obj, field_type)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/adapters/base.py", line 336, in represent\n    return self.representer.represent(obj, field_type)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 251, in represent\n    rv = self.get_representer_for_type(field_type)(rv, field_type)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 139, in __call__\n    return self.adapt(self.call(value, field_type))\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 133, in _call_with_extras\n    return self.inner_call(value, **extras)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/representers/__init__.py", line 124, in _inner_call\n    return self.obj.f(self.representer, value, **kwargs)\n  File "/home/rogoberto/web2py/gluon/packages/dal/pydal/representers/base.py", line 141, in _reference\n    return str(long(value))\nValueError: invalid literal for long() with base 10: \'venda_praso\'\n'
p11
s.